# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omniversion < Formula
  desc "Omniversion"
  homepage "https://layer9.berlin/"
  version "0.44.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omniversion/omniversion/releases/download/v0.44.0/brew_omniversion_0.44.0_darwin_arm64.tar.gz"
      sha256 "2eaa3d8a38bc93712c11775f20f0f0bdd4ba4eb0d271709b41ccc8d3010e5132"

      def install
        bin.install "omniversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omniversion/omniversion/releases/download/v0.44.0/brew_omniversion_0.44.0_darwin_amd64.tar.gz"
      sha256 "ae938813fca779bfac9237c2a5ca41700f38dd4a6ac36135ea707c88fef3c635"

      def install
        bin.install "omniversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/omniversion/omniversion/releases/download/v0.44.0/brew_omniversion_0.44.0_linux_amd64.tar.gz"
      sha256 "84d7c40db4cdc5ad71477c540346b2828ced25ec9c3e027f6c40ddcffa1f7787"

      def install
        bin.install "omniversion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omniversion/omniversion/releases/download/v0.44.0/brew_omniversion_0.44.0_linux_arm64.tar.gz"
      sha256 "45f257d0742efb7d6da9cbd4d08ca02b0a5178be4ba85da9baf4c6702fd505f3"

      def install
        bin.install "omniversion"
      end
    end
  end

  test do
    system "#{bin}/omniversion version"
  end
end
