# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omniversion < Formula
  desc "Omniversion"
  homepage "https://layer9.berlin/"
  version "0.43.15"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omniversion/omniversion/releases/download/v0.43.15/brew_omniversion_0.43.15_darwin_amd64.tar.gz"
      sha256 "b785bc1c1b283ac4bc068454a46dcb5317c6dc8c35329b5d22906c959a93754c"

      def install
        bin.install "omniversion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omniversion/omniversion/releases/download/v0.43.15/brew_omniversion_0.43.15_darwin_arm64.tar.gz"
      sha256 "2e52ce808119e5fd2de39f0303e2aabe97ea2c6fa06c5585194535c12340a1dc"

      def install
        bin.install "omniversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omniversion/omniversion/releases/download/v0.43.15/brew_omniversion_0.43.15_linux_arm64.tar.gz"
      sha256 "02b11a7ee505d308296e2a638522a7c481939dd73ff72587bcc0ea4a2a2e19aa"

      def install
        bin.install "omniversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omniversion/omniversion/releases/download/v0.43.15/brew_omniversion_0.43.15_linux_amd64.tar.gz"
      sha256 "3f4d8cfe3537ba713f9cda09b3317876576619b25b04e3f6a89ea9f9d3b8a989"

      def install
        bin.install "omniversion"
      end
    end
  end

  test do
    system "#{bin}/omniversion version"
  end
end
